#!/usr/bin/env sh

## Description: Wrapper around the normal rebuild function with added stuff.
## Usage: demo-setup
## Example: "ddev demo-setup"

# If its running confirm delete
if [ "$(ddev list | grep v2025demo | grep OK)" ]; then
  echo "The v2025demo is running. It will be deleted and recreated. Press ENTER to continue or CTRL-C to abort."
  read x
fi

# Delete garbage
ddev delete -O -y
rm -rf vendor web composer.* patches.lock.json

# Drupal CMS
ddev start

# Overwrite canvas with our version
rm -rf web/modules/contrib/canvas
cp -r merged_canvas/canvas web/modules/contrib/canvas

# Copy custom AB split test module
ddev exec bash -lc 'mkdir -p web/modules/custom && cp -a custom_modules/. web/modules/custom/'

# Install
ddev drush si drupal_cms_installer installer_site_template_form.add_ons=byte --account-pass=admin --site-name="2025 Demo" -y
# Install byte
#ddev install-byte

# Composer stuff
ddev composer require 'drupal/ai:1.2.x-dev@dev' \
'drupal/ai_agents:1.2.x-dev@dev' \
'drupal/ai_provider_openai:1.2.x-dev@dev' \
'drupal/ai_simple_pdf_to_text:^1.0@alpha' \
'drupal/ai_vdb_provider_milvus:1.1.x-dev@dev' \
'drupal/page_cache_exclusion:^1.0' \
'drupal/pexels_ai:^1.0@alpha' \
'jfcherng/php-diff:^6.0'

# AI Context via git.
cp -r custom_modules/ai_context web/modules/contrib/ai_context

ddev drush cr
# Install the AI stuff.
ddev drush recipe ../custom_recipes/canvas_ai_setup
ddev drush cr
# Add all images after to make sure they are indexed correctly.
ddev drush recipe ../custom_recipes/media_images
# Add Aidan's manual pages
ddev drush recipe ../custom_recipes/new_canvas_page
# Always flush the cache
ddev drush cr

# Install modules.
ddev drush en -y ab_split_test page_cache_exclusion context_content_watch

# Index the AI stuff
ddev drush sapi-i

echo "Visit https://v2025demo.ddev.site/canvas and login with user 'admin' and password 'admin' to see the demo page."
echo "After login, you click "New" and "New Page" to create a new page from AI."
