#!/usr/bin/env sh

## Description: Wrapper around the normal rebuild function with added stuff.
## Usage: demo-setup
## Example: "ddev demo-setup"

# If its running confirm delete
if [ "$(ddev list | grep v2025demo | grep OK)" ]; then
  echo "The v2025demo is running. It will be deleted and recreated. Press ENTER to continue or CTRL-C to abort."
  read x
fi

# Delete garbage
ddev delete -O -y
rm -rf vendor web composer.* patches.lock.json

# Drupal CMS
ddev start

# Overwrite canvas with our version
rm -rf web/modules/contrib/canvas
cp -r merged_canvas/canvas web/modules/contrib/canvas

# Install
ddev drush si -y --account-pass=admin --site-name="2025 Demo"
# Install a empty demo page with Canvas
ddev drush recipe ../custom_recipes/new_canvas_page
# Composer stuff
ddev composer require 'drupal/ai:1.2.x-dev@dev' 'drupal/ai_agents:1.2.x-dev@dev' 'drupal/ai_provider_openai:1.2.x-dev@dev' 'drupal/ai_vdb_provider_milvus:1.1.x-dev@dev' 'drupal/pexels_ai:^1.0@alpha'
ddev drush cr
# Install the AI stuff.
ddev drush recipe ../custom_recipes/canvas_ai_setup
ddev drush cr
# Add all images after to make sure they are indexed correctly.
ddev drush recipe ../custom_recipes/media_images

# Always flush the cache
ddev drush cr

# Index the AI stuff
ddev drush sapi-i

echo "Visit https://v2025demo.ddev.site/canvas/canvas_page/2/editor and login with user 'admin' and password 'admin' to see the demo page."
echo "After login, you click "New" and "New Page" to create a new page from AI."
