#!/bin/bash

## Description: Setup the Driesnote
## Usage: setup-demo
## Example: setup-demo
## ExecRaw: true

# If its running confirm delete
if [ "$(ddev list | grep v2025demo | grep OK)" ]; then
  read -p "v2025demo is running, do you want to delete it and re-setup? (y/n) " -n 1 -r
  echo    # (optional) move to a new line
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Deleting v2025demo"
  else
    echo "Exiting setup-demo"
    exit 1
  fi
fi

# Delete garbage
ddev delete -O -y
rm -rf .vscode config private recipes vendor web composer.* patches.lock.json

# Drupal CMS
ddev start
ddev drush si -y --account-pass=admin --site-name="Driesnote 2025 Demo"

# Mercury
ddev composer require drupal/twig_tweak drupal/twig_field_value
ddev drush pm:en -y twig_tweak twig_field_value
ddev drush cr
git clone git@git.drupal.org:project/mercury.git web/themes/contrib/mercury
ddev exec "cd web/themes/contrib/mercury && nvm install && $HOME/.local/share/pnpm/pnpm install"
ddev drush theme:en -y mercury
ddev drush config-set system.theme default mercury -y

# Uninstall the demo themes
ddev drush theme:un starshot_demo
ddev drush theme:un civictheme

# Remove the demo pages
ddev drush entity:delete -y canvas_page

# Install the new demoe page
ddev drush recipe ../custom_recipes/new_canvas_page

ddev drush cr

echo "Visit https://v2025demo.ddev.site/canvas/canvas_page/2/editor, login with admin/admin and create your first page!"
