id: node.page.full
status: true
content_entity_type_id: node
content_entity_type_bundle: page
content_entity_type_view_mode: full
dependencies:
  module:
    - node
  config:
    - canvas.component.sdc.mercury.heading
    - canvas.component.sdc.mercury.text
    - canvas.component.block.system_breadcrumb_block
    - node.type.page
    - core.entity_view_mode.node.full
component_tree:
  - uuid: 92e68054-9f78-4420-8752-96ec693d2fa9
    component_id: block.system_breadcrumb_block
    component_version: cec23aa503e2a02f
    inputs:
      label: Breadcrumbs
      label_display: '0'
  -
    uuid: f08be9dc-e328-4cb7-9499-df6db9bd8900
    component_id: sdc.mercury.heading
    component_version: cc29b01ba3415896
    inputs:
      heading_text:
        sourceType: dynamic
        expression: 'ℹ︎␜entity:node:page␝title␞␟value'
      level: 1
      styles: default
      align: left
      url: 'No URL'
  - uuid: caa1e4b2-d58b-4140-b99b-ab3e1ce55ad5
    component_id: sdc.mercury.text
    component_version: bbc797b76ac62b14
    inputs:
      text:
        sourceType: dynamic
        expression: 'ℹ︎␜entity:node:page␝field_content␞␟processed'
