name: Starter
type: Site
description: A simple template with the just basics. Bring your own design, and build what you need.
recipes:
  - core/recipes/administrator_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/document_media_type
  - drupal_cms_admin_ui
  - drupal_cms_anti_spam
  - drupal_cms_authentication
  - drupal_cms_privacy_basic
  - drupal_cms_remote_video
  - drupal_cms_seo_basic
  - easy_email_express
install:
  - automated_cron
  - automatic_updates
  - automatic_updates_extensions
  - canvas
  - dashboard
  - drupal_cms_helper
  - eca_base
  - eca_config
  - eca_content
  - eca_misc
  - eca_render
  - eca_ui
  - eca_user
  - gin_login
  - menu_link_content
  - mercury
  - menu_link_content
  - modeler_api
  - navigation
  - package_manager
  - project_browser
  - update
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - token
  - views_ui
  # This theme MUST be installed or Canvas breaks in strange ways.
  - canvas_stark
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  import:
    canvas: '*'
    image:
      - image.style.large
      - image.style.thumbnail
    user:
      - views.view.user_admin_people
  actions:
    dashboard.dashboard.welcome:
      addComponentsToLayout:
        # The list of Canvas pages.
        - section: 0
          position: 0
          component:
            region:
              layout_twocol_section: first
            default_region: content
            configuration:
              id: 'views_block:canvas_pages-block_1'
              label: ''
              label_display: visible
              provider: views
              context_mapping: { }
              views_label: ''
              items_per_page: null
        # The "recent content" block.
        - section: 0
          position: 1
          component:
            region:
              layout_twocol_section: first
            default_region: content
            configuration:
              id: 'views_block:recent_content-block_recent_content'
              label: ''
              label_display: visible
              provider: views
              context_mapping: { }
              views_label: ''
              items_per_page: null
    navigation.block_layout:
      # To prevent duplicated items if this recipe is applied more than once,
      # this needs to be changed as simple config. That's okay, though, because
      # even though Navigation treats this as a layout section, it's still just
      # a simple config object at heart.
      simpleConfigUpdate:
        # Add a link to the Drupal CMS user guide.
        sections.0.components.52e884dd-0301-4265-b2b3-9cea53a403f3:
          uuid: 52e884dd-0301-4265-b2b3-9cea53a403f3
          region: footer
          configuration:
            id: navigation_link
            label: Help
            label_display: '0'
            provider: navigation
            title: Help
            uri: 'https://new.drupal.org/docs/drupal-cms'
            icon_class: help
          weight: -2
          additional: []
    package_manager.settings:
      simpleConfigUpdate:
        additional_trusted_composer_plugins:
          # This is indirectly added by `drupal/core-dev`.
          - tbachert/spi
    project_browser.admin_settings:
      simpleConfigUpdate:
        enabled_sources:
          recommended:
            uri: 'https://git.drupalcode.org/api/v4/projects/157093/repository/files/recommended.yml/raw?ref=HEAD'
            ttl: 1
          drupalorg_jsonapi: []
        default_source: recommended
        allow_ui_install: true
        max_selections: 1
    system.site:
      simpleConfigUpdate:
        page.404: '/404'
    system.theme:
      simpleConfigUpdate:
        default: mercury
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        - 'access administration pages'
        - 'access contextual links'
        - 'access media overview'
        - 'access navigation'
        - 'administer url aliases'
        - 'create url aliases'
        - 'create canvas_page'
        - 'delete own files'
        - 'delete canvas_page'
        - 'edit canvas_page'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view own unpublished media'
        - 'view the administration theme'
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'delete own files'
        - 'view own unpublished content'
        - 'view welcome dashboard'
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
    core.menu.static_menu_link_overrides:
      simpleConfigUpdate:
        definitions.announcements_feed__announcement:
          menu_name: admin
          parent: system.admin
          weight: 0
          expanded: false
          enabled: false
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
    # Enable the name field in the entity form so it can be modified.
    core.entity_form_display.media.document.*:
      setComponent:
        name: name
        options:
          type: string_textfield
          weight: -1
          region: content
    update.settings:
      simpleConfigUpdate:
        check.disabled_extensions: true
